

export const columns = [
    {
      name: "ID",
      key: "id",
      keyForXLs: "id",
      numberic: true,
      autoFocus: true,
      edit: true,
      onlyRead: true,
      isRequired: false,
      numeric: true,
      filterabie: true,
    },
  
    {
      name: "Contact Person",
      key: "contactNameSurname",
      keyForXLs: "contactNameSurname",
      isRequired: false,
      autoFocus: true,
    },
    {
      name: "Contact Person Arm",
      key: "contactPersonArm",
      keyForXLS: "contactpersonArm",
      onlyRead: true,
      isRequired: false,
      autoFocus: true,
    },
    {
      name: "Company Name",
      key: "companyname",
      keyForXLS: "companyname",
      autoFocus: true,
    },
    {
      name: "Contact Person Arm",
      key: "contactPersonArms",
      keyForXLS: "contactpersonArm",
      onlyRead: true,
      isRequired: false,
      autoFocus: true,
    },
  
    {
      name: "Phone",
      key: "phone",
      keyForXLS: "phone",
      edit: true,
      onlyRead: true,
      isRequired: false,
      autoFocus: true,
    },
    {
      name: "Address",
      key: "address",
      edit: true,
      keyForXLS: "address",
      isRequired: false,
      autoFocus: true,
    },
    {
      name: "Email",
      key: "email",
      edit: true,
      keyForXLS: "email",
      isRequired: false,
      autoFocus: true,
    },
    {
      name: "Download vouche",
      key: "downloadvouche",
      keyForXLS: "downloadvouche",
      isRequired: false,
      autoFocus: true,
      filterabie: true,
    },
    {
      name: "Role",
      key: "role",
      keyForXLS: "role",
      edit: true,
      isRequired: false,
      autoFocus: true,
      filterabie: true,
    },
    {
      name: "Status",
      key: "status",
      edit: true,
      keyForXLS: "status",
      filterabie: true,
      autoFocus: true,
    },
    {
      name: "Balance",
      key: "balance",
      keyForXLS: "balance",
      numeric: true,
      edit: true,
      isRequired: false,
      autoFocus: true,
      filterabie: true,
    },
    {
      name: "Creation Data",
      key: "data",
      keyForXLS: "data",
      isRequired: false,
      autoFocus: true,
      numeric: true,
      edit: true,
      filterabie: true,
    },
  ];
  
  export const rowstable = [
    {
      key: 1,
      id: 1000314,
      person: "AAAAAAAAAAA",
      personArm: "աաաաաաաաաաաա",
      name: "AAAAA",
      nameArm: "աաաա",
      phone: +132465798,
      address: "YEREVAN",
      email: "vahag.hloyan@smartsoft.am",
      vocter: "---",
      role: "Admin",
      status: "Aproved",
      balance: 0.0,
      data: "06-09-2023",
    },
    {
      key: 2,
      id: 1000313,
      person: "NAJRI POGHOSYAN",
      personArm: "Նաիրի Պողքսյան",
      name: "SCHWARZ LLC",
      nameArm: "Շվարղ ՍՊԸ",
      phone: +37433100666,
      address: "HANRAPETUTYAN 9",
      email: "nairipoghosyan@yandex.com",
      vocter: "---",
      role: "user",
      status: "Not Verified",
      balance: 0.0,
      data: "27-07-2023",
    },
    {
      key: 3,
      id: 1000309,
      person: "GAYA KANDARYAN",
      personArm: "Գայա Կանդարյան",
      name: "KANDA TRAVEL",
      nameArm: "Կանդա Թրավել",
      phone: +37460512010,
      address: "49/2 NALBANDYAN STREET, 0025",
      email: "gaya.kandaryan@kandacluc.com",
      vocter: "Only paid",
      role: "Admin",
      status: "Aproved",
      balance: " 4.750.00",
      data: "17-02-2023",
    },
    {
      key: 4,
      id: 1000299,
      person: "ZARUHI POGHOSYAN",
      personArm: "Զարուհի Պողոսյան",
      name: "KANDA TRAVEL CLUB",
      nameArm: "Կանդա Թրավել Քլաբ",
      phone: +37443581515,
      address: "NALBANDYAN 49",
      email: "booking@kandaclub.com",
      vocter: "---",
      role: "Admin",
      status: "Aproved",
      balance: 0.0,
      data: "28-12-2022",
    },
    {
      key: 5,
      id: 1000050,
      person: "SMART SOFT",
      personArm: "ՍՄԱՐԹՍՐՖԹ",
      name: "SMART SOFT",
      nameArm: "ՍՄԱՐԹՍՐՖԹ",
      phone: +37415552255,
      address: "HAKOB HAKOBYAN 3",
      email: "support@smartsoft.am",
      vocter: "All",
      role: "Admin",
      status: "Aproved",
      balance: 0.0,
      data: "04-02-2022",
    },
  ];
  export const roww = [
    "Contact Person",
    "Contact Person Arm",
    "Company Name",
    "Address",
    "Email",
    "Status",
  ];
  
  export const rowstablemoreEdit = [{ name: "Edit", key: "edit", link: "edit" }];
  